export default {
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  LOAD_COURSES: "LOAD_COURSES",
  CREATE_AUTHOR: "CREATE_AUTHOR",
  LOAD_AUTHORS: "LOAD_AUTHORS"
};
